name: publish2pypi

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Update version in pyproject.toml
      run: |
        RELEASE=${GITHUB_REF##*/}
        # Remove 'v' prefix if present in tag
        RELEASE=${RELEASE#v}
        # Update version in pyproject.toml - using a more precise pattern
        sed -i "s/version = \"[^\"]*\"/version = \"$RELEASE\"/" pyproject.toml
        echo "Version set to: $RELEASE"
        cat pyproject.toml
    - name: Install build and twine
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build package
      run: python -m build
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*